// Generated by CoffeeScript 1.8.0
(function() {
  var fetchAllModel, fetchFile, fetchModelKeyList, getAllModelBy, memorizeGetAllModel, pkg, serverImagePath, serverImagePath100;

  if (app.fn == null) {
    app.fn = {};
  }

  pkg = app.fn;

  serverImagePath = function(path) {
    var filepath;
    filepath = app.tool.serverapi.filepath("http://" + window.location.host);
    return filepath(path);
  };

  serverImagePath100 = function(path) {
    var filepath;
    filepath = app.tool.serverapi.filepathWithSize("http://" + window.location.host, 100, 100);
    return filepath(path);
  };

  fetchFile = function(path) {
    var query;
    query = app.tool.serverapi.query("http://" + window.location.host);
    return query(app.tool.serverapi.ServeFile, {
      FilePath: path
    });
  };

  fetchModelKeyList = function(path) {
    var promise;
    promise = $.Deferred();
    fetchFile(path).done(function(data) {
      var modelKey;
      if (data.Success) {
        return promise.resolve((function() {
          var _i, _len, _ref, _results;
          _ref = data.Info;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            modelKey = _ref[_i];
            if (modelKey !== 'config.json') {
              _results.push(modelKey);
            }
          }
          return _results;
        })());
      } else {
        return promise.reject(data.Info);
      }
    }).fail(function(err) {
      return promise.reject(err);
    });
    return promise;
  };

  fetchAllModel = function(path) {
    return function(keys) {
      var key, promise;
      promise = $.Deferred();
      $.when.apply($, (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = keys.length; _i < _len; _i++) {
          key = keys[_i];
          _results.push(fetchFile("" + path + "/" + key + "/config.json"));
        }
        return _results;
      })()).done(function() {
        var details;
        details = arguments;
        return promise.resolve(_.zip(keys, details));
      }).fail(function(err) {
        return promise.reject(err);
      });
      return promise;
    };
  };

  getAllModelBy = function(configPath) {
    return function(type) {
      var promise;
      promise = $.Deferred();
      fetchFile(configPath).done(function(config) {
        var pkgPath;
        pkgPath = config[type];
        return fetchModelKeyList(pkgPath).pipe(fetchAllModel(pkgPath)).done(function(ret) {
          return promise.resolve(config, ret);
        }).fail(function(err) {
          return promise.reject(err);
        });
      }).fail(function(err) {
        return promise.reject(err);
      });
      return promise;
    };
  };

  memorizeGetAllModel = function(cache) {
    return function(configPath) {
      return function(type) {
        var cacheKey, promise;
        cacheKey = "" + configPath + "/" + type;
        promise = $.Deferred();
        if (cache[cacheKey] != null) {
          setTimeout(function() {
            return promise.resolve(cache[cacheKey]);
          }, 0);
        } else {
          getAllModelBy(configPath)(type).done(function(ret) {
            return promise.resolve(ret);
          }).fail(function(err) {
            return promise.reject(err);
          });
        }
        return promise;
      };
    };
  };

  pkg.getAllModelBy = getAllModelBy;

  pkg.serverImagePath = serverImagePath;

  pkg.serverImagePath100 = serverImagePath100;

}).call(this);
