// Generated by CoffeeScript 1.8.0
(function() {
  if (app.tool == null) {
    app.tool = {};
  }

  app.tool.getFullBase64str = function(base64str) {
    return 'data:image/png;base64,' + base64str;
  };

  app.tool.getFullDay = function(unixtime) {
    var date;
    date = new Date(unixtime * 1000);
    return date.getFullYear() + '/' + (date.getMonth() + 1) + '/' + date.getDate();
  };

  app.tool.getUnixTimeByYMD = function(year, month, day) {
    var datum;
    datum = new Date(Date.UTC(year, month - 1, day, 0, 0, 0));
    return datum.getTime() / 1000;
  };

  app.tool.getUnixTime = function() {
    return Math.round((new Date()).getTime() / 1000);
  };

}).call(this);
