application: academic-actor-87312
version: 1
runtime: go
api_version: go1

handlers:
- url: /goapp/.*
  script: _go_app
- url: /test
  static_dir: test
- url: /(.+)
  static_files: web/\1
  upload: web/(.+)
- url: /
  static_files: web/index.html
  upload: web/index.html

