application: academic-actor-87312
version: 1
runtime: go
api_version: go1

handlers:
- url: /sdyle
  static_dir: ../web/static4
- url: /cljs
  static_dir: ../web/static4
- url: /angular-test-coffee
  static_dir: ../web/static3
- url: /angular-test
  static_dir: ../web/static2
- url: /static
  static_dir: ../web/static
- url: /.*
  script: _go_app
