(ns core.event)
(def OnPage1BtnClick (new js/Rx.Subject))
(def OnPage2BtnClick (new js/Rx.Subject))
(def OnPage1AddHpBtnClick (new js/Rx.Subject))
(def OnMenubarBtnClick (new js/Rx.Subject))
(def OnStreetSnapListBtnClick (new js/Rx.Subject))