goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.string.StringBuffer', 'goog.array']);
goog.addDependency("../test/rxjs.js", ['test.rxjs'], ['cljs.core']);
goog.addDependency("../app2/design/IPage.js", ['app2.design.IPage'], ['cljs.core']);
goog.addDependency("../app2/impl/Page.js", ['app2.impl.Page'], ['app2.design.IPage', 'cljs.core']);
goog.addDependency("../app/controller.js", ['app.controller'], ['cljs.core']);
goog.addDependency("../app/page/DefaultController.js", ['app.page.DefaultController'], ['cljs.core']);
goog.addDependency("../app/page/MenubarController.js", ['app.page.MenubarController'], ['app.controller', 'cljs.core', 'app.page.DefaultController']);
goog.addDependency("../app/page/DefaultView.js", ['app.page.DefaultView'], ['cljs.core']);
goog.addDependency("../app/event.js", ['app.event'], ['cljs.core']);
goog.addDependency("../app/page.js", ['app.page'], ['cljs.core']);
goog.addDependency("../app/page/MenubarView.js", ['app.page.MenubarView'], ['app.page.DefaultView', 'app.event', 'cljs.core', 'app.page']);
goog.addDependency("../test/ns2.js", ['test.ns2'], ['cljs.core']);
goog.addDependency("../test/ns1.js", ['test.ns1'], ['app.event', 'cljs.core', 'app.Main', 'test.ns2']);
goog.addDependency("../app2/design/IApp.js", ['app2.design.IApp'], ['cljs.core']);
goog.addDependency("../app2/design/IPageManager.js", ['app2.design.IPageManager'], ['cljs.core']);
goog.addDependency("../app2/impl/App.js", ['app2.impl.App'], ['cljs.core', 'app2.design.IApp', 'app2.design.IPageManager']);
goog.addDependency("../app2/main.js", ['app2.main'], ['cljs.core', 'app2.design.IApp', 'app2.impl.App']);
goog.addDependency("../app/page/HeaderView.js", ['app.page.HeaderView'], ['app.page.DefaultView', 'app.event', 'cljs.core', 'app.page']);
goog.addDependency("../app/page/HeaderController.js", ['app.page.HeaderController'], ['app.controller', 'cljs.core', 'app.page.DefaultController', 'app.page']);
goog.addDependency("../app.js", ['app'], ['app.controller', 'app.page.HeaderController', 'app.event', 'app.page.MenubarController', 'cljs.core', 'app.page.HeaderView', 'app.page.MenubarView']);