// Generated by CoffeeScript 1.8.0
(function() {
  if (app.tool == null) {
    app.tool = {};
  }

  app.tool.getFullBase64str = function(base64str) {
    return 'data:image/png;base64,' + base64str;
  };

}).call(this);
