// Generated by CoffeeScript 1.8.0
(function() {
  var ABC;

  ABC = (function() {
    function ABC() {}

    ABC.prototype.doA = function() {
      return alert("D");
    };

    return ABC;

  })();

}).call(this);
